---
- name: Get show ip int brief information
  hosts: all
  gather_facts: false

  tasks:
    - name: Grab a show command
      raw: "show ip int brief" 

      register: print_output

    - debug: var=print_output.stdout_lines

